version: '2.3'
services:
  nginx:
    image: library/nginx:1.17.9
    container_name: seiu-nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/nginx.hosts.local.conf:/etc/nginx/conf.d/default.conf
        #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #- /etc/letsencrypt:/etc/certs/
        #- /etc/letsencrypt/archive/bitdropdemo.seiudsa.com-0001:/etc/certs/archive:ro
  lufi:
    build: .
    expose:
      - 8080
    #ports:
     # - "8080:8080"
    volumes:
      - ./lufi.conf:/home/lufi/lufi.conf
      - ./data:/home/lufi/data
      - ./themes:/opt/lufi/themes
#      - ./files:/home/lufi/files
    entrypoint: ["/entrypoint.sh"]
