
server { listen *:80 default_server;
return 301 https://$host$request_uri;}

server {
  
  listen *:443 ssl default_server;
  server_name _;

  charset utf-8;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
  ssl_prefer_server_ciphers on;
  ssl_certificate /etc/certs/live/bitdropdemo.seiudsa.com-0001/fullchain.pem;
ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384";
  ssl_certificate_key /etc/certs/live/bitdropdemo.seiudsa.com-0001/privkey.pem;
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;


    location ^~ /new/upload {
        proxy_pass http://lufi:8080;
       proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }

      location ^~ /new/download {
        proxy_pass http://lufi:8080;
       proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }

    location ^~ /new {
    limit_except GET HEAD POST PUT DELETE PATCH {
      allow 127.0.0.1;
    }
    proxy_pass http://lufi:8080;
       proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
   }
  location ~ ^/([\/]) {
  proxy_pass http://lufi:8080$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;

  }

  location ~ ^/([0-9A-Za-z]) {

    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;


  return 301  http://$host/old$request_uri;
    }



  location / {
    return 301 http://$host/new$request_uri;
  }

  location ^~/old {
  proxy_pass http://bitdrop-old.seiu.org/;
   #proxy_set_header Host $host:$server_port;
   proxy_set_header X-Real-IP $remote_addr;
  }






}
